---
# This playbook contains common plays that will be run on all nodes.

- name: Check SO distro and version
  fail: msg="Invalid SO"
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version != '14.04'

- name: Install security updates
  apt: pkg=unattended-upgrades state=present

- name: Check for reboot need
  stat: path=/var/run/reboot_required
  register: reboot_required

- name: Restart the server
  become: true
  become_method: sudo
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: reboot_required.stat.exists == True

- name: Waiting for server to come back
  become: false
  local_action: wait_for host={{ inventory_hostname }}
                state=started
  when: reboot_required.stat.exists == True

- name: Install ntp
  apt: name=ntp state=present update_cache=true
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: start the ntp service
  service: name=ntp state=started enabled=yes
  tags: ntp

- name: test to see if apparmor is running
  command: apparmor_status
  register: apparmorstatus
  changed_when: false