---
# Variables listed here are applicable to all host groups

ntpserver: a.st1.ntp.br

# apache
apacheconfig: /etc/apache2/
apachegroupid: 1010
apachegroupname: apache
apacheuserid: 1010
apacheusername: apache
applicationpath: /var/www/html

# postgresql
databasename: appdatabase
appusername: appuser
appuserpass: apppassword
databaseconfig: /etc/postgresql/9.3/main/