---
- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache=true state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc

- name: Install PostgreSQL server
  apt: name={{ item }} update_cache=true state=installed
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Create the config files
  become: yes
  become_user: postgres
  vars:
    ipv4_netmask: "{{ ansible_default_ipv4.network }}/{{ ansible_default_ipv4.netmask }}"
  template: src={{ item }}.conf dest={{databaseconfig}}/{{ item }}.conf
  with_items:
    - postgresql
    - pg_hba
  notify: restart postgresql

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  become: yes
  become_user: postgres
  postgresql_db: name={{databasename}} encoding='UTF-8' lc_collate='C' lc_ctype='C' template='template0' state=present

- name: Ensure application user has access to the database
  become: yes
  become_user: postgres
  postgresql_user: db={{databasename}} name={{appusername}} password={{appuserpass}} priv=ALL state=present

- name: Ensure user does not have unnecessary privileges
  become: yes
  become_user: postgres
  postgresql_user: name={{appusername}} role_attr_flags=NOSUPERUSER,NOCREATEDB state=present